# 驼人腕管超声数据集 包含耦合剂的空背景图像
data_root: /home/t_wanghan/work/data/WanGuan-zhuanjiaWithBG
img_dir: JPEGImages
mask_dir: Masks

class_rgb_dir: SegmentationClass
object_dir: SegmentationObject

img_suffix: .png
mask_suffix: .png

num_classes: 12
num_training_samples: 1053
num_validation_samples: 453
image_height: 920
image_width: 1270

mean:
  train_data: [0.069, 0.074, 0.077]
  imagenet: [0.485, 0.456, 0.406]

std:
  train_data: [0.116, 0.126, 0.134]
  imagenet: [0.229, 0.224, 0.225]

normalize_type: imagenet

classes: [
  0—背景,
  1-大多角骨,
  2-尺动脉,
  3-拇长屈肌腱,
  4-指浅屈肌腱,
  5-指深屈肌腱,
  6-桡侧腕屈肌腱,
  7-正中神经,
  8-腕横韧带,
  9-舟状骨,
  10-豌豆骨,
  11-钩骨
]

color_map: [
  [0,0,0],
  [15,195,166],
  [182,18,45],
  [212,60,243],
  [238,92,164],
  [243,175,106],
  [164,31,230],
  [233,196,84],
  [123,204,245],
  [73,205,231],
  [248,111,133],
  [191,224,25]
]
